# Generated by Django 3.1.7 on 2021-03-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phq9test',
            name='date_taken',
            field=models.DateField(auto_now_add=True),
        ),
    ]
