# Generated by Django 3.1.7 on 2021-03-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210316_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phq9test',
            name='date_taken',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
