# Generated by Django 3.1.7 on 2021-03-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210316_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='phq9test',
            name='ans1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phq9test',
            name='ans2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phq9test',
            name='ans3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phq9test',
            name='ans4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phq9test',
            name='ans5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phq9test',
            name='ans6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phq9test',
            name='ans7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phq9test',
            name='ans8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phq9test',
            name='ans9',
            field=models.IntegerField(default=0),
        ),
    ]
