# Generated by Django 3.1.7 on 2021-03-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210320_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phq9test',
            name='ans1',
        ),
        migrations.RemoveField(
            model_name='phq9test',
            name='ans2',
        ),
        migrations.RemoveField(
            model_name='phq9test',
            name='ans3',
        ),
        migrations.RemoveField(
            model_name='phq9test',
            name='ans4',
        ),
        migrations.RemoveField(
            model_name='phq9test',
            name='ans5',
        ),
        migrations.RemoveField(
            model_name='phq9test',
            name='ans6',
        ),
        migrations.RemoveField(
            model_name='phq9test',
            name='ans7',
        ),
        migrations.RemoveField(
            model_name='phq9test',
            name='ans8',
        ),
        migrations.RemoveField(
            model_name='phq9test',
            name='ans9',
        ),
    ]
