# Generated by Django 3.1.7 on 2021-03-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210322_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='phq9test',
            name='ans1',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
        migrations.AddField(
            model_name='phq9test',
            name='ans2',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
        migrations.AddField(
            model_name='phq9test',
            name='ans3',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
        migrations.AddField(
            model_name='phq9test',
            name='ans4',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
        migrations.AddField(
            model_name='phq9test',
            name='ans5',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
        migrations.AddField(
            model_name='phq9test',
            name='ans6',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
        migrations.AddField(
            model_name='phq9test',
            name='ans7',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
        migrations.AddField(
            model_name='phq9test',
            name='ans8',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
        migrations.AddField(
            model_name='phq9test',
            name='ans9',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
    ]
