# Generated by Django 3.1.7 on 2021-04-06 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_phq9test_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phq9test',
            name='ans1',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'A few times'), (2, 'Sometimes'), (3, 'Often')], default=0),
        ),
        migrations.AlterField(
            model_name='phq9test',
            name='ans2',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'A few times'), (2, 'Sometimes'), (3, 'Often')], default=0),
        ),
        migrations.AlterField(
            model_name='phq9test',
            name='ans3',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'A few times'), (2, 'Sometimes'), (3, 'Often')], default=0),
        ),
        migrations.AlterField(
            model_name='phq9test',
            name='ans4',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'A few times'), (2, 'Sometimes'), (3, 'Often')], default=0),
        ),
        migrations.AlterField(
            model_name='phq9test',
            name='ans5',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'A few times'), (2, 'Sometimes'), (3, 'Often')], default=0),
        ),
        migrations.AlterField(
            model_name='phq9test',
            name='ans6',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'A few times'), (2, 'Sometimes'), (3, 'Often')], default=0),
        ),
        migrations.AlterField(
            model_name='phq9test',
            name='ans7',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'A few times'), (2, 'Sometimes'), (3, 'Often')], default=0),
        ),
        migrations.AlterField(
            model_name='phq9test',
            name='ans8',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'A few times'), (2, 'Sometimes'), (3, 'Often')], default=0),
        ),
        migrations.AlterField(
            model_name='phq9test',
            name='ans9',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'A few times'), (2, 'Sometimes'), (3, 'Often')], default=0),
        ),
        migrations.CreateModel(
            name='generalized_anxiety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans1', models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day'), (4, 'Constantly')], default=0)),
                ('ans2', models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day'), (4, 'Constantly')], default=0)),
                ('ans3', models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day'), (4, 'Constantly')], default=0)),
                ('ans4', models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day'), (4, 'Constantly')], default=0)),
                ('ans5', models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day'), (4, 'Constantly')], default=0)),
                ('ans6', models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day'), (4, 'Constantly')], default=0)),
                ('ans7', models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day'), (4, 'Constantly')], default=0)),
                ('ans8', models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day'), (4, 'Constantly')], default=0)),
                ('total_score', models.IntegerField()),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('percentage', models.FloatField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
