# Generated by Django 3.1.7 on 2021-04-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210406_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalized_anxiety',
            name='ans1',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'A few times'), (2, 'Sometimes'), (3, 'Often'), (4, 'Constantly')], default=0),
        ),
        migrations.AlterField(
            model_name='generalized_anxiety',
            name='ans2',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'A few times'), (2, 'Sometimes'), (3, 'Often'), (4, 'Constantly')], default=0),
        ),
        migrations.AlterField(
            model_name='generalized_anxiety',
            name='ans3',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'A few times'), (2, 'Sometimes'), (3, 'Often'), (4, 'Constantly')], default=0),
        ),
        migrations.AlterField(
            model_name='generalized_anxiety',
            name='ans4',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'A few times'), (2, 'Sometimes'), (3, 'Often'), (4, 'Constantly')], default=0),
        ),
        migrations.AlterField(
            model_name='generalized_anxiety',
            name='ans5',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'A few times'), (2, 'Sometimes'), (3, 'Often'), (4, 'Constantly')], default=0),
        ),
        migrations.AlterField(
            model_name='generalized_anxiety',
            name='ans6',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'A few times'), (2, 'Sometimes'), (3, 'Often'), (4, 'Constantly')], default=0),
        ),
        migrations.AlterField(
            model_name='generalized_anxiety',
            name='ans7',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'A few times'), (2, 'Sometimes'), (3, 'Often'), (4, 'Constantly')], default=0),
        ),
        migrations.AlterField(
            model_name='generalized_anxiety',
            name='ans8',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'A few times'), (2, 'Sometimes'), (3, 'Often'), (4, 'Constantly')], default=0),
        ),
        migrations.AlterField(
            model_name='phq9test',
            name='ans1',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
        migrations.AlterField(
            model_name='phq9test',
            name='ans2',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
        migrations.AlterField(
            model_name='phq9test',
            name='ans3',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
        migrations.AlterField(
            model_name='phq9test',
            name='ans4',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
        migrations.AlterField(
            model_name='phq9test',
            name='ans5',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
        migrations.AlterField(
            model_name='phq9test',
            name='ans6',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
        migrations.AlterField(
            model_name='phq9test',
            name='ans7',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
        migrations.AlterField(
            model_name='phq9test',
            name='ans8',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
        migrations.AlterField(
            model_name='phq9test',
            name='ans9',
            field=models.IntegerField(choices=[(0, 'Not at All'), (1, 'Several Days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0),
        ),
    ]
