# Generated by Django 3.1.7 on 2021-04-06 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0012_major_depressive'),
    ]

    operations = [
        migrations.CreateModel(
            name='manic_episodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans1', models.IntegerField(choices=[(0, 'Not at All'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=0)),
                ('ans2', models.IntegerField(choices=[(0, 'Not at All'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=0)),
                ('ans3', models.IntegerField(choices=[(0, 'Not at All'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=0)),
                ('ans4', models.IntegerField(choices=[(0, 'Not at All'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=0)),
                ('ans5', models.IntegerField(choices=[(0, 'Not at All'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=0)),
                ('ans6', models.IntegerField(choices=[(0, 'Not at All'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=0)),
                ('ans7', models.IntegerField(choices=[(0, 'Not at All'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=0)),
                ('ans8', models.IntegerField(choices=[(0, 'Not at All'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe')], default=0)),
                ('total_score', models.IntegerField()),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('percentage', models.FloatField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
