# Generated by Django 3.1.7 on 2021-04-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_manic_episodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phq9test',
            name='id',
        ),
        migrations.AddField(
            model_name='phq9test',
            name='user1',
            field=models.CharField(default='mugdha', max_length=100, primary_key=True, serialize=False),
        ),
    ]
