# Generated by Django 3.1.7 on 2021-04-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20210414_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalized_anxiety',
            name='id',
        ),
        migrations.RemoveField(
            model_name='major_depressive',
            name='id',
        ),
        migrations.RemoveField(
            model_name='manic_episodes',
            name='id',
        ),
        migrations.RemoveField(
            model_name='panicdisorder',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post_traumaticstress',
            name='id',
        ),
        migrations.AddField(
            model_name='generalized_anxiety',
            name='user1',
            field=models.CharField(default='mugdha', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='major_depressive',
            name='user1',
            field=models.CharField(default='mugdha', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='manic_episodes',
            name='user1',
            field=models.CharField(default='mugdha', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='panicdisorder',
            name='user1',
            field=models.CharField(default='mugdha', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='post_traumaticstress',
            name='user1',
            field=models.CharField(default='mugdha', max_length=100, primary_key=True, serialize=False),
        ),
    ]
